### ISSUE TITLE
Help wanted for a web app project

### ISSUE THREAD

**Issue by yilaili** [TokisakiYuu/TokisakiYuu#1]
你好！我是密歇根大学的在读博后，在程序员客栈看到你的页面跟到这里来的。我这边有一个web app的项目（react + nodejs）想找一些developer，有偿（走学校的经费），不知道你是否有兴趣？项目现在已经有了个prototype，也有一些本科生一起做，如果你感兴趣的话我可以把repo share给你。我的微信号是xylthx，或者我们先github联系也可以。冒昧打扰了！

**Comment by tokisakiyuu** [comment]
> 你好！我是密歇根大学的在读博后，在程序员客栈看到你的页面跟到这里来的。我这边有一个web app的项目（react + nodejs）想找一些developer，有偿（走学校的经费），不知道你是否有兴趣？项目现在已经有了个prototype，也有一些本科生一起做，如果你感兴趣的话我可以把repo share给你。我的微信号是xylthx，或者我们先github联系也可以。冒昧打扰了！

微信加你了
